# kind: Service
# apiVersion: v1
# metadata:
#   name: train-schedule-service
# spec:
#   type: NodePort
#   selector:
#     app: train-schedule
#   ports:
#   - protocol: TCP
#     port: 80
#     nodePort: 8080

apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: train-schedule
  selector:
    app: train-schedule
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule        
        image: ${DOCKER_IMAGE_NAME}:${IMAGE_TAG}
        # imagePullPolicy: Always
        ports:
        - containerPort: 8080
